export interface TourDay {
  day: number
  title: string
  activities: string[]
  meals: string[]
  accommodation?: string
}

export interface Tour {
  id: string
  title: string
  category: string
  price: string
  duration: string
  rating: string
  image: string
  badge?: string
  description: string
  highlights: string[]
  includes: string[]
  excludes: string[]
  itinerary: TourDay[]
  location: string
  groupSize: string
  difficulty: string
  bestTime: string
}

export const toursData: Tour[] = [
  {
    id: 'sahara-desert-adventure',
    title: 'Sahara Desert Adventure',
    category: 'desert',
    price: '7,800 MAD',
    duration: '4 Days',
    rating: '4.9',
    image: 'https://images.unsplash.com/photo-1510952267577-fc96d5ca660a?w=1200&auto=format&fit=crop&q=80&ixlib=rb-4.1.0',
    badge: 'Popular',
    description: 'Experience the magic of the Sahara Desert with camel trekking, traditional Berber camps, and breathtaking sunsets over golden dunes.',
    highlights: [
      'Camel trekking through Erg Chebbi dunes',
      'Overnight stay in luxury desert camp',
      'Traditional Berber music and dance',
      'Stargazing under the desert sky',
      'Sunrise over the Sahara',
    ],
    includes: [
      'Transportation in 4x4 vehicle',
      'Professional guide',
      'Camel trekking',
      'Desert camp accommodation',
      'All meals (breakfast, lunch, dinner)',
      'Traditional entertainment',
    ],
    excludes: [
      'International flights',
      'Travel insurance',
      'Personal expenses',
      'Tips for guides',
    ],
    location: 'Merzouga, Morocco',
    groupSize: '2-12 people',
    difficulty: 'Moderate',
    bestTime: 'October - April',
    itinerary: [
      {
        day: 1,
        title: 'Arrival in Merzouga',
        activities: [
          'Pick up from your hotel in Marrakech or Ouarzazate',
          'Scenic drive through the Atlas Mountains',
          'Arrive in Merzouga and check into hotel',
          'Sunset camel ride to the edge of the dunes',
          'Return to hotel for dinner',
        ],
        meals: ['Dinner'],
        accommodation: 'Hotel in Merzouga',
      },
      {
        day: 2,
        title: 'Desert Adventure Begins',
        activities: [
          'Early morning breakfast',
          '4x4 drive to the desert camp',
          'Camel trekking through Erg Chebbi',
          'Lunch at the camp',
          'Sandboarding on the dunes',
          'Sunset viewing from the highest dune',
          'Traditional Berber dinner',
          'Music and dance around the campfire',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Luxury Desert Camp',
      },
      {
        day: 3,
        title: 'Desert Exploration',
        activities: [
          'Sunrise camel ride',
          'Breakfast at the camp',
          'Visit to nomadic Berber families',
          'Explore the desert oasis',
          'Quad biking (optional)',
          'Return to camp for lunch',
          'Relaxation and stargazing',
          'Evening entertainment',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Luxury Desert Camp',
      },
      {
        day: 4,
        title: 'Return Journey',
        activities: [
          'Final sunrise in the desert',
          'Breakfast at the camp',
          'Camel ride back to Merzouga',
          'Visit to local market',
          'Lunch in Merzouga',
          'Return journey to Marrakech',
          'Drop off at your hotel',
        ],
        meals: ['Breakfast', 'Lunch'],
      },
    ],
  },
  {
    id: 'imperial-cities-tour',
    title: 'Imperial Cities Tour',
    category: 'cities',
    price: '10,950 MAD',
    duration: '7 Days',
    rating: '4.8',
    image: 'https://images.unsplash.com/photo-1624805098931-098c0d918b34?w=1200&auto=format&fit=crop&q=80&ixlib=rb-4.1.0',
    description: 'Discover Morocco\'s four imperial cities: Rabat, Meknes, Fes, and Marrakech. Explore ancient medinas, royal palaces, and vibrant souks.',
    highlights: [
      'Visit all four imperial cities',
      'Explore UNESCO World Heritage sites',
      'Traditional Moroccan architecture',
      'Local markets and souks',
      'Authentic Moroccan cuisine',
    ],
    includes: [
      'All transportation',
      'Professional guide',
      'Hotel accommodations',
      'All breakfasts',
      'Entrance fees to monuments',
    ],
    excludes: [
      'International flights',
      'Lunches and dinners',
      'Travel insurance',
      'Personal expenses',
    ],
    location: 'Rabat, Meknes, Fes, Marrakech',
    groupSize: '2-15 people',
    difficulty: 'Easy',
    bestTime: 'Year-round',
    itinerary: [
      {
        day: 1,
        title: 'Rabat - The Capital',
        activities: [
          'Arrival in Rabat',
          'Visit Hassan Tower and Mausoleum',
          'Explore the Royal Palace',
          'Walk through the Kasbah of the Udayas',
          'Traditional dinner in the medina',
        ],
        meals: ['Dinner'],
        accommodation: 'Hotel in Rabat',
      },
      {
        day: 2,
        title: 'Meknes - The Ismaili Capital',
        activities: [
          'Travel to Meknes',
          'Visit Bab Mansour gate',
          'Explore the Royal Stables',
          'Lunch in the medina',
          'Visit Moulay Ismail Mausoleum',
          'Evening at leisure',
        ],
        meals: ['Breakfast', 'Lunch'],
        accommodation: 'Hotel in Meknes',
      },
      {
        day: 3,
        title: 'Fes - The Spiritual Capital',
        activities: [
          'Travel to Fes',
          'Visit the Royal Palace',
          'Explore the ancient medina',
          'Lunch in traditional restaurant',
          'Visit Al-Qarawiyyin University',
          'Shopping in the souks',
        ],
        meals: ['Breakfast', 'Lunch'],
        accommodation: 'Riad in Fes',
      },
      {
        day: 4,
        title: 'Fes Exploration',
        activities: [
          'Visit the tanneries',
          'Explore the Jewish Quarter',
          'Lunch break',
          'Visit pottery workshops',
          'Traditional cooking class',
          'Evening cultural show',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Riad in Fes',
      },
      {
        day: 5,
        title: 'Journey to Marrakech',
        activities: [
          'Travel to Marrakech via Ifrane',
          'Stop at Azrou cedar forest',
          'Lunch in Beni Mellal',
          'Arrive in Marrakech',
          'Check into riad',
          'Evening in Jemaa el-Fnaa square',
        ],
        meals: ['Breakfast', 'Lunch'],
        accommodation: 'Riad in Marrakech',
      },
      {
        day: 6,
        title: 'Marrakech Discovery',
        activities: [
          'Visit Koutoubia Mosque',
          'Explore Bahia Palace',
          'Visit Saadian Tombs',
          'Lunch in the medina',
          'Shopping in souks',
          'Evening food tour',
        ],
        meals: ['Breakfast', 'Lunch'],
        accommodation: 'Riad in Marrakech',
      },
      {
        day: 7,
        title: 'Marrakech & Departure',
        activities: [
          'Visit Majorelle Garden',
          'Explore Yves Saint Laurent Museum',
          'Final shopping',
          'Lunch',
          'Transfer to airport',
        ],
        meals: ['Breakfast', 'Lunch'],
      },
    ],
  },
  {
    id: 'atlas-mountains-trek',
    title: 'Atlas Mountains Trek',
    category: 'mountains',
    price: '5,200 MAD',
    duration: '3 Days',
    rating: '5.0',
    image: 'https://images.unsplash.com/photo-1560789590-ee4cc7125967?w=1200&auto=format&fit=crop&q=80&ixlib=rb-4.1.0',
    badge: 'New',
    description: 'Trek through the stunning Atlas Mountains, visit traditional Berber villages, and experience authentic mountain life.',
    highlights: [
      'Trekking in the High Atlas Mountains',
      'Visit traditional Berber villages',
      'Homestay with local families',
      'Mountain landscapes and valleys',
      'Traditional Berber cuisine',
    ],
    includes: [
      'Professional mountain guide',
      'Mule for luggage',
      'All meals',
      'Homestay accommodations',
      'Transportation to/from Marrakech',
    ],
    excludes: [
      'International flights',
      'Travel insurance',
      'Personal trekking equipment',
      'Tips',
    ],
    location: 'High Atlas Mountains',
    groupSize: '2-8 people',
    difficulty: 'Moderate to Challenging',
    bestTime: 'March - November',
    itinerary: [
      {
        day: 1,
        title: 'Ascent to Imlil',
        activities: [
          'Pick up from Marrakech',
          'Drive to Imlil village',
          'Meet your guide and muleteer',
          'Begin trek to Tizi n\'Tamatert pass',
          'Lunch with mountain views',
          'Continue to Tacheddirt village',
          'Homestay with Berber family',
        ],
        meals: ['Lunch', 'Dinner'],
        accommodation: 'Berber Homestay',
      },
      {
        day: 2,
        title: 'Mountain Villages',
        activities: [
          'Breakfast with the family',
          'Trek through beautiful valleys',
          'Visit traditional Berber homes',
          'Lunch in the mountains',
          'Continue to Imsker village',
          'Learn about Berber culture',
          'Evening with local family',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Berber Homestay',
      },
      {
        day: 3,
        title: 'Return Journey',
        activities: [
          'Early morning breakfast',
          'Final trek through the mountains',
          'Visit local market',
          'Lunch in Imlil',
          'Return to Marrakech',
          'Drop off at hotel',
        ],
        meals: ['Breakfast', 'Lunch'],
      },
    ],
  },
  {
    id: 'coastal-paradise',
    title: 'Coastal Paradise',
    category: 'coast',
    price: '6,200 MAD',
    duration: '5 Days',
    rating: '4.7',
    image: 'https://images.unsplash.com/photo-1613057157282-cc3cbe630b26?q=80&w=1200&auto=format&fit=crop&ixlib=rb-4.1.0',
    description: 'Explore Morocco\'s stunning Atlantic coast from Casablanca to Essaouira, with beautiful beaches and historic medinas.',
    highlights: [
      'Visit Casablanca and Hassan II Mosque',
      'Explore Essaouira\'s medina',
      'Beach activities and water sports',
      'Fresh seafood cuisine',
      'Historic Portuguese architecture',
    ],
    includes: [
      'All transportation',
      'Professional guide',
      'Hotel accommodations',
      'All breakfasts',
      'Beach activities',
    ],
    excludes: [
      'International flights',
      'Lunches and dinners',
      'Water sports equipment rental',
      'Personal expenses',
    ],
    location: 'Casablanca, Essaouira',
    groupSize: '2-12 people',
    difficulty: 'Easy',
    bestTime: 'May - September',
    itinerary: [
      {
        day: 1,
        title: 'Casablanca Arrival',
        activities: [
          'Arrival in Casablanca',
          'Visit Hassan II Mosque',
          'Explore the Corniche',
          'Lunch by the sea',
          'City tour',
          'Evening at leisure',
        ],
        meals: ['Dinner'],
        accommodation: 'Hotel in Casablanca',
      },
      {
        day: 2,
        title: 'Journey to Essaouira',
        activities: [
          'Breakfast and check out',
          'Drive to Essaouira',
          'Stop at Oualidia for lunch',
          'Arrive in Essaouira',
          'Check into hotel',
          'Evening walk along the beach',
        ],
        meals: ['Breakfast', 'Lunch'],
        accommodation: 'Hotel in Essaouira',
      },
      {
        day: 3,
        title: 'Essaouira Exploration',
        activities: [
          'Visit the medina',
          'Explore the port and fish market',
          'Lunch with fresh seafood',
          'Beach activities',
          'Visit the Skala fortifications',
          'Sunset on the beach',
        ],
        meals: ['Breakfast', 'Lunch'],
        accommodation: 'Hotel in Essaouira',
      },
      {
        day: 4,
        title: 'Beach Day',
        activities: [
          'Full day at the beach',
          'Water sports (optional)',
          'Lunch at beach restaurant',
          'Relaxation and swimming',
          'Evening in the medina',
        ],
        meals: ['Breakfast', 'Lunch'],
        accommodation: 'Hotel in Essaouira',
      },
      {
        day: 5,
        title: 'Return to Casablanca',
        activities: [
          'Breakfast and check out',
          'Final shopping in Essaouira',
          'Return journey to Casablanca',
          'Lunch on the way',
          'Transfer to airport',
        ],
        meals: ['Breakfast', 'Lunch'],
      },
    ],
  },
  {
    id: 'marrakech-express',
    title: 'Marrakech Express',
    category: 'cities',
    price: '5,200 MAD',
    duration: '3 Days',
    rating: '4.9',
    image: 'https://images.unsplash.com/photo-1624805098931-098c0d918b34?w=1200&auto=format&fit=crop&q=80&ixlib=rb-4.1.0',
    description: 'A quick but comprehensive tour of Marrakech, the Red City, with its vibrant souks, historic palaces, and lively squares.',
    highlights: [
      'Explore the medina and souks',
      'Visit historic palaces',
      'Experience Jemaa el-Fnaa square',
      'Traditional Moroccan hammam',
      'Cooking class',
    ],
    includes: [
      'Hotel accommodation',
      'Professional guide',
      'All breakfasts',
      'Entrance fees',
      'Hammam experience',
    ],
    excludes: [
      'International flights',
      'Lunches and dinners',
      'Travel insurance',
      'Personal expenses',
    ],
    location: 'Marrakech',
    groupSize: '2-10 people',
    difficulty: 'Easy',
    bestTime: 'Year-round',
    itinerary: [
      {
        day: 1,
        title: 'Arrival & Medina Tour',
        activities: [
          'Arrival in Marrakech',
          'Check into riad',
          'Explore the medina',
          'Visit Bahia Palace',
          'Lunch in traditional restaurant',
          'Shopping in souks',
          'Evening in Jemaa el-Fnaa',
        ],
        meals: ['Dinner'],
        accommodation: 'Riad in Marrakech',
      },
      {
        day: 2,
        title: 'Historic Marrakech',
        activities: [
          'Breakfast at riad',
          'Visit Koutoubia Mosque',
          'Explore Saadian Tombs',
          'Visit Majorelle Garden',
          'Lunch break',
          'Traditional hammam experience',
          'Evening cooking class',
        ],
        meals: ['Breakfast', 'Dinner'],
        accommodation: 'Riad in Marrakech',
      },
      {
        day: 3,
        title: 'Departure',
        activities: [
          'Breakfast at riad',
          'Final shopping',
          'Visit Yves Saint Laurent Museum',
          'Lunch',
          'Transfer to airport',
        ],
        meals: ['Breakfast', 'Lunch'],
      },
    ],
  },
  {
    id: 'desert-mountains',
    title: 'Desert & Mountains',
    category: 'desert',
    price: '11,900 MAD',
    duration: '8 Days',
    rating: '4.9',
    image: 'https://images.unsplash.com/photo-1510952267577-fc96d5ca660a?w=1200&auto=format&fit=crop&q=80&ixlib=rb-4.1.0',
    badge: 'Best Value',
    description: 'The ultimate Moroccan adventure combining the Atlas Mountains and Sahara Desert for an unforgettable journey.',
    highlights: [
      'Atlas Mountains trekking',
      'Sahara Desert experience',
      'Traditional Berber villages',
      'Camel trekking',
      'Luxury desert camp',
    ],
    includes: [
      'All transportation',
      'Professional guides',
      'All accommodations',
      'All meals',
      'Camel trekking',
      'Desert camp',
    ],
    excludes: [
      'International flights',
      'Travel insurance',
      'Personal expenses',
      'Tips',
    ],
    location: 'Atlas Mountains & Sahara Desert',
    groupSize: '2-12 people',
    difficulty: 'Moderate',
    bestTime: 'October - April',
    itinerary: [
      {
        day: 1,
        title: 'Marrakech to Imlil',
        activities: [
          'Pick up from Marrakech',
          'Drive through Atlas Mountains',
          'Arrive in Imlil',
          'Trek to Berber village',
          'Homestay experience',
        ],
        meals: ['Lunch', 'Dinner'],
        accommodation: 'Berber Homestay',
      },
      {
        day: 2,
        title: 'Mountain Trekking',
        activities: [
          'Full day trekking',
          'Visit Berber villages',
          'Mountain lunch',
          'Continue trek',
          'Evening with local family',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Berber Homestay',
      },
      {
        day: 3,
        title: 'Journey to Desert',
        activities: [
          'Breakfast and departure',
          'Drive to Ouarzazate',
          'Visit Ait Benhaddou',
          'Continue to Dades Valley',
          'Check into hotel',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Hotel in Dades',
      },
      {
        day: 4,
        title: 'Todra Gorge & Merzouga',
        activities: [
          'Visit Todra Gorge',
          'Lunch in Tinghir',
          'Drive to Merzouga',
          'Arrive at desert edge',
          'Check into hotel',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Hotel in Merzouga',
      },
      {
        day: 5,
        title: 'Desert Adventure',
        activities: [
          'Camel trek into desert',
          'Arrive at luxury camp',
          'Lunch at camp',
          'Sandboarding',
          'Sunset viewing',
          'Traditional dinner',
          'Music and stargazing',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Luxury Desert Camp',
      },
      {
        day: 6,
        title: 'Desert Exploration',
        activities: [
          'Sunrise camel ride',
          'Breakfast at camp',
          'Visit nomad families',
          'Desert activities',
          'Return to camp',
          'Evening entertainment',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Luxury Desert Camp',
      },
      {
        day: 7,
        title: 'Return Journey',
        activities: [
          'Final desert sunrise',
          'Camel ride back',
          'Drive to Ouarzazate',
          'Lunch break',
          'Continue to Marrakech',
          'Check into hotel',
        ],
        meals: ['Breakfast', 'Lunch', 'Dinner'],
        accommodation: 'Hotel in Marrakech',
      },
      {
        day: 8,
        title: 'Departure',
        activities: [
          'Breakfast at hotel',
          'Final shopping',
          'Transfer to airport',
        ],
        meals: ['Breakfast'],
      },
    ],
  },
]

export function getTourById(id: string): Tour | undefined {
  return toursData.find((tour) => tour.id === id)
}

